service: aws-api-test

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"

functions:
  app-api:
    handler: handler.handler
    events: 
      - http: 
          path: /
          method: get
          cors: true
      - http: 
          path: /{proxy+}
          method: any
          cors: true
